notifications:
  email: false

branches:
  only:
    #- master
    - 1.0

matrix:
  include:
    - os: osx
      sudo: required
      language: generic
    - os: linux
      sudo: required
      language: generic
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      sudo: required
      language: generic
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run --rm -v $PWD:/io $DOCKER_IMAGE $PRE_CMD /io/scripts/build-wheels-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then scripts/build-wheels-macos.sh; fi
  - ls dist/

deploy:
  provider: releases
  api_key:
    secure: qtLJf1SzA5nLwd0HOUUttcNecWo+YcECZduC4gYjto4Gp/IXFE9zvCakJeohveYSKJngwMjOPP3GuWdOU7v5o5wjaOVsb3dfgrjOBdb9Ftu5csd96mp0T1/fcPvt2QdldurAyiVSssT4zApbPqXLU5vESym2F0nCCsdeI4FARd2/VbvB/bqnRTPyblpNXMcs0wMC3SLBj3iVhAGnwHH1mlty6vfmgWViLhT8PHty3LHCGgTS023BskQlgx/BwUQdG2oCO2254T9WPxDoBaodfpwgK/yr2HZzwHaDAmgbccx8DgPHy3Bn1M2Cg6XmxR+rW/griPSZ1APzJcPxCNuJ0GNfxrswhV68b1Lbcds9de6SMuQgJ5TLDBmufCIoVZ4QDwXHdr0xrQe183GxJ9QhsuGwEJ0180D4OW+n88iISnUSZa6eE5zhzfSpxv38jZNdzujfYmNuqgXlszRzLJnZ7SjVvpU8LXUfm4rRHclKUa8HD7WWlf5BsZMSh8nYdCG7ahFwzQLc14X37da+WyQUKZ3abaxKoy10LRrrL/FwQJGPBxnsDmbklwMDgNHQL/1ViRdsisymxV9SbSFRrqz4VAzMw+mbCNnLbz8PHvSJ2QTGmPvhfWg2tUAGnlq1mb8KfMQIVizf4Wid16l6PFQkQD9M2FIcuNaBzGdp39PN8lg=
  file_glob: true
  file: dist/*.whl
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
